---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin-service
spec:
  ports:
  - name: web
    port: 8096
    protocol: TCP
    targetPort: 8096
    nodePort: 30046
  selector:
    app: jellyfin
  type: NodePort
